from ImageBasicProperties import TestImageBasicProperties
from MatrixPointerBasicProperties import TestMatrixPointerBasicProperties

test_cases = [TestImageBasicProperties, TestMatrixPointerBasicProperties]


